### ISSUE TITLE
likes-ratings plugin not compatible with search plugin

### ISSUE THREAD

**Issue by awrog** [trilbymedia/grav-plugin-likes-ratings#1]
Great plugin!
I use the following shortcode at the end of a page: `{{ likes_ratings() }}`
A user noticed some errors, while searching with the standard search plugin, that look related to the likes-rating plugin:

**Server Error**
Sorry, something went terribly wrong!
0 - Return value of Grav\Plugin\LikesRatings\Likes::getId() must be of the type string, null returned

example: https://lrp-netwerk.pkn.nl/search/query:brieven

When I replace `{{ likes_ratings() }}` with `{{ likes_ratings('my-string') }}`, then the error disappears.

**Comment by rhukster** [comment]
Thanks for catching this.. it's been fixed and released in v1.0.3. (should be available in an hour)

Cheers.
